server:
  port: 7675
spring:
  redis:
    host: 10.111.10.8
    database: 4
    port: 6379
    password: duduadmin
    pool:
      max-active: 300
      max-wait: -1
      max-idle: 300
      min-idle: 0
    timeout: 3000
  jta:
    log-dir: /data/apps/logs/shop-operation/
    atomikos:
      properties:
        log-base-dir: /data/apps/logs/shop-operation/
  http:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB
  cloud:
    stream:
      kafka:
        binder:
          zk-nodes: 10.111.10.243:2181
          brokers: 10.111.10.243:9092
          autoCreateTopics: true
          autoAddPartitions: true
      bindings:
        group-order-gen:
          destination: group_order_msg_press
          group: group_order_press
          producer:
            partitionCount: 2
        return-order:
          destination: return_order_msg_press
          group: return_order_press
          producer:
            partitionCount: 2
        async-export-in:
          destination: async_export_msg_press
          group: async_export_press
        async-export-out:
          destination: async_export_msg_press
          group: async_export_press
          producer:
            partitionCount: 2
        go-chef-hours:
          destination: go_chef_press
          group: go_chef_press
          partitionCount: 2
        group-order-deal:
          destination: group_order_deal_msg_press
          group: group_order_deal_press
          consumer:
            maxAttempts: 1
        stock-sku-pre-num-out:
          destination: stock_sku_pre_num_msg_press
          group: stock_sku_pre_num_press
          producer:
            partitionCount: 2
        stock-spu-pre-num-out:
          destination: stock_spu_pre_num_msg_press
          group: stock_spu_pre_num_press
          producer:
            partitionCount: 2
        goods-update-out:
          destination: goods_update_out_msg_press
          group: gooods_update_out_press
          producer:
            partitionCount: 2
        sales-plan-goods-update:
          destination: goods_update_out_msg_press
          group: sales_plan_goods_update_press
          consumer:
            maxAttempts: 1
  kafka:
    consumer:
      enable-auto-commit: false
zuul:
  host:
      socket-timeout-millis: 60000
      connect-timeout-millis: 60000
  retryable: true
  ignoredServices: '*'
  sensitive-headers:
  routes:
    shop-mobile:
      path: /mobile/**
      strPrefix: true
      serviceId: shop-mobile
    shop-bd:
      path: /bd/**
      strPrefix: true
      serviceId: shop-bd
    shop-tms-mgr:
      path: /tms-mgr/**
      strPrefix: true
      serviceId: shop-tms-mgr
    shop-purchase-mgr:
      path: /purchase-mgr/**
      strPrefix: true
      serviceId: shop-purchase-mgr
    shop-comment-mgr:
      path: /comment-mgr/**
      strPrefix: true
      serviceId: shop-comment-mgr

hikari:
  order:
    jdbc-url: jdbc:mysql://rm-2zersbhevj8idaw24.mysql.rds.aliyuncs.com:3306/vvshop_order?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: shop
    password: adam@zhouj1
    maximum-pool-size: 80
    pool-name: order
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000
  orderRead:
    jdbc-url: jdbc:mysql://rm-2zersbhevj8idaw24.mysql.rds.aliyuncs.com:3306/vvshop_order?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: shop
    password: adam@zhouj1
    maximum-pool-size: 80
    pool-name: orderRead
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000    
  returnOrder:
    jdbc-url: jdbc:mysql://rm-2zersbhevj8idaw24.mysql.rds.aliyuncs.com:3306/vvshop_return_order?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: shop
    password: adam@zhouj1
    maximum-pool-size: 80
    pool-name: returnOrder
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000
  goods:
    jdbc-url: jdbc:mysql://rm-2zersbhevj8idaw24.mysql.rds.aliyuncs.com:3306/vvshop_goods?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: shop
    password: adam@zhouj1
    maximum-pool-size: 80
    pool-name: goods
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000
  goodsRead:
    jdbc-url: jdbc:mysql://rm-2zersbhevj8idaw24.mysql.rds.aliyuncs.com:3306/vvshop_goods?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: shop
    password: adam@zhouj1
    maximum-pool-size: 80
    pool-name: goodsRead
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000    
  bi:
    jdbc-url: jdbc:mysql://rm-2zersbhevj8idaw24.mysql.rds.aliyuncs.com:3306/vvshop_bi?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: shop
    password: adam@zhouj1
    maximum-pool-size: 80
    pool-name: bi
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000
  user:
    jdbc-url: jdbc:mysql://rm-2zersbhevj8idaw24.mysql.rds.aliyuncs.com:3306/vvshop_user?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: shop
    password: adam@zhouj1
    maximum-pool-size: 80
    pool-name: user
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000
  member:
    jdbc-url: jdbc:mysql://rm-2zersbhevj8idaw24.mysql.rds.aliyuncs.com:3306/vvshop_member?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: shop
    password: adam@zhouj1
    maximum-pool-size: 80
    pool-name: member
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000
  distribution:
    jdbc-url: jdbc:mysql://rm-2zersbhevj8idaw24.mysql.rds.aliyuncs.com:3306/vvshop_distribution?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: shop
    password: adam@zhouj1
    maximum-pool-size: 80
    pool-name: distribution
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000
  competitor:
    jdbc-url: jdbc:mysql://rm-2zersbhevj8idaw24.mysql.rds.aliyuncs.com:3306/vvshop_bi?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: shop
    password: adam@zhouj1
    maximum-pool-size: 80
    pool-name: competitor
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000
  platform:
    jdbc-url: jdbc:mysql://rm-2zersbhevj8idaw24.mysql.rds.aliyuncs.com:3306/vvshop_platform?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: shop
    password: adam@zhouj1
    maximum-pool-size: 80
    pool-name: platform
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000
  purchase:
    jdbc-url: jdbc:mysql://rm-2zersbhevj8idaw24.mysql.rds.aliyuncs.com:3306/vvshop_purchase?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: shop
    password: adam@zhouj1
    maximum-pool-size: 80
    pool-name: purchase
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000

eureka:
  instance:
    prefer-ip-address: true
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
kdn:
  appkey: 1ca5291e-f401-4762-a959-5f007d9b786b
  requrl: http://api.kdniao.cc/Ebusiness/EbusinessOrderHandle.aspx
  ebusinessid: 1345292

qiniu:
  accessKey: uzRSzrJlUGa_e_Z77AvkcGMYSmo1oyxlRG9luQ3-
  secretKey: LuTVBTq1N9j8tGFRbJVTk0YYqvwZWD6SektFsjIz
  domain: https://dimage.songshupinpin.com
  bucket: songshu-dev
  pipeline: adam-zip
  notifyUrl: http://prefix.luotuojinrong.cn/customer-manager/camel/customer/qiniu/pfop/notify
cache:
  database:
    goods: 7
    order: 7

xxl:
  job:
    executor:
      logpath: /data/apps/logs/shop-operation
      appname: press-shop-operation-job-executor
      port: 9991
      ip:
    admin:
      addresses: http://10.111.10.8:8080/xxl-job-admin
    accessToken:

logging:
  config: classpath:logback-spring.xml

procurement:
  isreal: true
  current:
    envStr: 'dev'

repay:
  switch: false

metabase:
  site:
    url: https://metabase.songshupinpin.com
  embedding:
    secret:
      key: 3c7541313a5c2444353b0bce917de83cf7f92d40cc4a802fa28211f941dbe14f

autoSettle:
  batchCount:
    scanDisRecord: 1
    scanDisUser: 1
    settle: 1
create:
  group-order-batch-size: 500

batch:
  upload:
    spuOrSku:
      zipDir: /data/upload/spuOrSku/zip/
      unzipDir: /data/upload/spuOrSku/unzip/

category:
  version: V2.0
